django/cicu/urls.py
from django.conf.urls import patterns, url, include


urlpatterns = patterns('cicu.views',
    url(r'^$', 'upload', name='upload-image'),
    url(r'^crop$', 'crop', name='image-crop'),
    url(r'^upload-profile-picture$', 'upload_profile_picture', name='image-upload'),
    url(r'^crop-profile-picture$', 'crop_profile_picture', name='image-crop'),
)

django/django_server/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from user_app.views import StaticTagViewSet
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users', include('user_app.urls')),
    url(r'^accounts/', include('user_auth.urls')),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^all-tags', include('taggit.urls')),
    url(r'^tags', StaticTagViewSet.as_view()),
    url(r'^workouts/', include('workouts.urls')),
    url(r'^messages/', include('messages.urls')),
    url(r'^upload-image/', include('cicu.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^membership/', include('membership.urls')),
    url(r'^calendar/', include('schedule.urls')),
    url(r'^feed', include('feed.urls')),
    url(r'^notifications', include('notifications.urls')),
)


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #static
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    #media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),


) + urlpatterns

django/workouts/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from rest_framework import routers

from workouts.views import VideoListView, VideoObjectView, TitleViewSet, CommentObjView, VideoLikeView
from workouts.views import CommentListView


router = routers.SimpleRouter(trailing_slash=False)
#router.register('comments', CommentViewSet)


urlpatterns = patterns('',
    url(r'^video?$', VideoListView.as_view()),
    url(r'^video/(?P<pk>[0-9]+)$', VideoObjectView.as_view()),
    url(r'^video/comments/(?P<pk>[0-9]+)$', CommentListView.as_view()),
    url(r'^video/likes/(?P<pk>[0-9]+)$', VideoLikeView.as_view()),
    url(r'^comments/(?P<pk>[0-9]+)$', CommentObjView.as_view()),
    url(r'^titles?$', TitleViewSet.as_view()),
)

django/workouts/models.py
#Django Libs
from django.db import models
#Python Libs
from time import time, gmtime, strftime
from user_app.models import Professional
from django.contrib.auth import get_user_model
User = get_user_model()
# from tagging.fields import TagField
from taggit.managers import TaggableManager
import datetime
from django.db.models import permalink
from django.contrib.comments.moderation import CommentModerator, moderator
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


# fs = FileSystemStorage(location='/home/miguel/Desktop/')


#Video Model
class Video(models.Model):
    user = models.ForeignKey(Professional, related_name='videos', blank=True,null=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True,null=True)
    title = models.CharField(max_length = 200, blank=True,null=True)
    description = models.TextField('description', null=True, blank=True)
    pub_date = models.DateTimeField('date published', default=now, null=True, blank=True)
    url_video = models.CharField(max_length = 200, blank=True,null=True)
    img = models.ImageField(upload_to="workout", blank=True, default='default-profile.svg')
    video_tags = TaggableManager(blank=True, verbose_name='video')
    likes = models.IntegerField(blank=True, null=True, default=0)
    likes_user = models.ManyToManyField(User, related_name='video_like', blank=True,null=True)
    views = models.IntegerField(blank=True, null=True, default=0)
    # file = models.FileField(upload_to='videos', storage=fs, blank=True, null=True)

    DIFFICULTY_CHOICES = (
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced')
    )
    difficulty = models.CharField(max_length=30, blank=True, choices=DIFFICULTY_CHOICES, default='beginner')


    #Metadata
    def __unicode__(self):
        return self.title


# @receiver(pre_delete, sender=Video)
# def video_delete(sender, instance, **kwargs):
#     instance.file.delete(False)


#Video Model
class VideoComment(models.Model):
    user = models.ForeignKey(User, blank=True,null=True)
    video =  models.ForeignKey(Video, related_name="comments")
    comment = models.TextField('description', null=True, blank=True)
    pub_date = models.DateTimeField('date published', default=now, null=True, blank=True)


    #Metadata

django/workouts/forms.py
#Django Libs
from django.contrib import auth
from django import forms
#Python Libs
from time import time, gmtime, strftime
#Models
from models import VideoComment, Video



class VideoCommentForm(forms.ModelForm):
    pub_date = forms.DateTimeField(initial = strftime("%m/%d/%y %H:%M", gmtime()))

    class Meta:
        model = VideoComment
        fields = ('video_id', 'user', 'comment', 'pub_date')


class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ('user', 'title', 'description', 'difficulty')

    def __init__(self, *args, **kargs):
        super(VideoForm, self).__init__(*args, **kargs)

django/workouts/views.py
from datetime import timedelta
from django.utils.timezone import utc, now
from rest_framework import viewsets, status, filters
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.decorators import api_view, authentication_classes, permission_classes, action, link
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser
from rest_framework.filters import SearchFilter
from rest_framework import generics
from django.contrib.auth import get_user_model
User = get_user_model()
from workouts.models import Video, VideoComment
from workouts.filters import DifficultyFilterBackend, WorkoutTagFilterBackend
from workouts.serializers import TitleSerializer, VideoSerializer, VideoCommentSerializer, CommentSerializer, VideoLikeSerializer
from workouts.permissions import IsAdminOrSelf
from notifications import notify


class VideoListView(generics.ListAPIView):
    model = Video
    permission_classes = (IsAuthenticated,)
    paginate_by = 9
    filter_backends = (DifficultyFilterBackend, WorkoutTagFilterBackend, SearchFilter,)
    search_fields = ('title', )


class VideoObjectView(generics.RetrieveUpdateDestroyAPIView):
    model = Video
    permission_classes = (IsAuthenticated,)
    serializer_class = VideoSerializer


class VideoLikeView(generics.UpdateAPIView):
    model = Video
    permission_classes = (IsAuthenticated,)
    serializer_class = VideoLikeSerializer


class CommentListView(generics.ListCreateAPIView):
    paginate_by = 5
    model = VideoComment
    permission_classes = (IsAuthenticated,)
    filter_backends = (filters.OrderingFilter, filters.SearchFilter,)
    serializer_class = CommentSerializer
    ordering = ('-pub_date',)
    def get_queryset(self):
        video_id = self.kwargs['pk']
        return VideoComment.objects.filter(video=video_id)

    # def post_save(self, obj, created=False):
    #     if User.objects.filter(id = obj.video.user_id).exists():
    #         notify.send(obj.user, recipient=obj.video.user, verb=u'commented on your video!')


class CommentObjView(generics.RetrieveUpdateDestroyAPIView):
    model = VideoComment
    permission_classes = (IsAdminOrSelf,)
    filter_backends = (filters.OrderingFilter, filters.SearchFilter,)


class TitleViewSet(generics.ListAPIView):
    paginate_by = None
    serializer_class = TitleSerializer
    model = Video
    permission_classes = (IsAuthenticated,)
    search_fields = ('title', )

django/workouts/templates/workout_videos/edit.html
{% extends "base.html" %}
{% block content %}


{% if request.user.is_superuser %}

{% for video in videos %}
<span class="thumbnail">
    <h2><a href="/workouts/video-edit/{{video.id}}/">{{video.title}}</a></h2>
</span>
{% endfor %}

{% else %}
<h1>Get Out</h1>
{% endif %}


{% endblock %}

django/workouts/templates/workout_videos/video.html
<div>
    <div class="row">
        <div class="col-xs-12">
        <div class="workout-video-shadow">
            <video width="640" height="480" class="video-js vjs-default-skin vjs-big-play-centered vjs-lef" controls preload="auto"
                   poster="/media/{{ video.img }}"
                   data-setup='{"techOrder": ["flash", "html5"]}'>
                <source src='rtmp://206.225.86.237:1935/vod/_definst_/mp4:{{ video.url_video }}' type='rtmp/mp4'/>
                <source src='http://206.225.86.237:1935/vod/content/{{ video.url_video }}/playlist.m3u8'
                        type='video/mp4'/>
            </video>
        </div>
            <header class="page-header">
                <h1>
                    {{ video.title }}
                    <small class="pull-right">Views: <span class="blue">{{ video.views }}</span></small>
                </h1>
            </header>
            <p class="clearfix">
                {% if request.user in video.likes_user.all %}
                    <button id="likeButton" type="button" class="btn btn-primary" data-val="unlike">unlike <span
                            class="glyphicon glyphicon-thumbs-down"></span></button>
                {% else %}
                    <button id="likeButton" type="button" class="btn btn-primary" data-val="like">like <span
                            class="glyphicon glyphicon-thumbs-up"></span></button>
                {% endif %}
                <big class="pull-right">Likes: <span id="likeCount" class="blue">{{ video.likes }}</span></big>
            </p>
            <div class="lead"><span class="blue">Description: </span>{{ video.description }}</div>
            <div class="lead"><span class="blue">Tags: </span>
                {% for video_tags in video.tags.names %}
                    <a href="#workoutsHeader" class="tag tag-click">{{ video_tags }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% if comments %}
    <section id="comments" class="panel panel-info">
        <div class="panel-heading">
            Comments
        </div>
        {% for object in comments reversed %}
            <ol id="comment-list" class="list-group">
                <li id="comment-1-by-nicolas-gonzalez"
                    class="comment vcard list-group-item box1 authenticated-comment staff-comment superuser-comment">
                    <div class="row">
                        <div class="col-xs-12 col-sm-3">
                            <img src="/media/{{ object.user.img }}" class="gravatar photo img-thumbnail">
                        </div>
                        <div class="col-xs-12 col-sm-9">
                            <span class="fn"><a href="/profile/view?id={{ object.user.id }}">{{ object.user.first_name }}{{ object.user.last_name }}</a></span>
                            on
                            <abbr class="comment-published">
                                {{ object.pub_date }}
                            </abbr>
                            <p>{{ object.comment }}</p>
                        </div>
                    </div>
                </li>
            </ol>
        {% endfor %}
    </section>
{% else %}
    <p>
        No comments yet.
    </p>
{% endif %}



<form action="/workouts/videocomment/" method="post" id="comment-form" class="well form-horizontal">{% csrf_token %}
    <fieldset>
        <legend>Post your comment</legend>
        <input id="id_video_id" name="video_id" type="hidden" value="{{ video.pk }}">
        <div>
            <div class="form-group">
                <label for="id_comment" class="col-lg-2 control-label">Comment</label>
                <div class="col-lg-10">
                    <textarea id="id_comment" class="form-control" rows="10" name="comment"></textarea>

                </div>
            </div>
        </div>
        <p class="auth">
            Comment as <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong>
        </p>
        <p class="submit">
            <input type="submit" name="submit" class="submit-post btn btn-primary submit-preview" value="Post">
        </p>
    </fieldset>
</form>
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script type="text/javascript" src="/static/js/bowser.js"></script>
<script type="text/javascript" src="/static/js/video.js"></script>
<script>
    videojs.options.flash.swf = "/static/js/video-js.swf"
</script>

<script>
    $(document).ready(function () {
        $("#unlike").click(function () {
            $.ajax({url: "/workouts/unlike/", data: { pk: {{video.pk}} }, type: "GET", dataType: "html", success: function (result) {
                $("#unlike1").html(result);
                $("#unlike2").html('<button id="like" type="button" class="btn btn-primary">like</button>');
            }});
        });
    });
</script>

<script>
    $(document).ready(function () {
        var $video = $('.video-js'),
                $likeCount = $("#likeCount"),
                $likeButton = $("#likeButton");
        $likeButton.click(function () {
            var bool = $likeButton.data('val') == "like";
            $.ajax({
                url: bool ? "/workouts/like/" : "/workouts/unlike",
                data: { pk: {{video.pk}} },
                type: "GET",
                dataType: "html",
                success: function (result) {
                    $likeButton.data('val', bool ? 'unlike' : 'like');
                    $likeButton.html(bool ? 'unlike <span class="glyphicon glyphicon-thumbs-down"></span>' : 'like <span class="glyphicon glyphicon-thumbs-up"></span>');
                    $likeCount.html(result);
                }
            });
        });
        $video.height($video.width() * 0.75);
        $(window).resize(function () {
            $video.height($video.width() * 0.75);
        });
    });
</script>

django/workouts/templates/workout_videos/video_edit.html
{% extends "base.html" %}
{% block content %}

{% if request.user.is_superuser %}

<div class="containerlogin">
    <h2>Edit Video</h2>
    <form action="" method="post">{% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input class='button' type='submit' name='submit' value='submit' />
    </form>
</div>

{% else %}
<h1>Get Out</h1>
{% endif %}


{% endblock %}